"""Static validation of report/dashboard.html.

The dashboard is a single self-contained file whose charts are generated by inline JS, so a
syntax error would produce a blank page rather than an error anyone would notice. This checks
the structure and extracts the script for a Node syntax check where Node is available.
"""
import re
import json
import subprocess
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
p = ROOT / "report" / "dashboard.html"
html = p.read_text(encoding="utf-8")

checks = []


def ck(label, cond, detail=""):
    checks.append((label, cond, detail))
    print(f"  {'PASS' if cond else 'FAIL'}  {label}" + (f"   {detail}" if detail else ""))


print("=" * 90)
print("DASHBOARD VALIDATION")
print("=" * 90)

ck("File exists and is non-trivial", len(html) > 100_000, f"{len(html)/1024:.0f} KB")
ck("Has doctype and title", html.startswith("<!doctype html>") and "<title>" in html)
ck("No unreplaced template placeholder", "__PAYLOAD__" not in html)
ck("No external resource references",
   not re.search(r'(src|href)\s*=\s*["\']https?://', html),
   "fully self-contained")

# Every nav button must have a matching page container and a router entry
navs = set(re.findall(r'data-p="([a-z]+)"', html))
pages = set(re.findall(r'id="p-([a-z]+)"', html))
ck("Nav buttons match page containers", navs == pages, f"{sorted(navs)}")
router = set(re.findall(r"(\w+):page[A-Z]\w+", html))
ck("Router covers every page", navs <= router, f"router={sorted(router)}")

# Extract and parse the embedded JSON payload
m = re.search(r"const D = (\{.*?\});\n", html, re.S)
ck("Embedded data payload found", bool(m))
if m:
    try:
        data = json.loads(m.group(1))
        ok = True
    except Exception as e:
        data, ok = {}, False
        print(f"        JSON parse error: {e}")
    ck("Payload is valid JSON", ok)
    if ok:
        required = ["kpis", "trend", "region", "merchants", "voucherType", "priority",
                    "anomalies", "forecast", "answers", "confounder", "ml", "recon"]
        missing = [k for k in required if k not in data]
        ck("Payload has every required key", not missing, f"missing={missing}" if missing else
           f"{len(data)} keys")
        ck("25 merchants present", len(data.get("merchants", [])) == 25)
        ck("7 months of trend present", len(data.get("trend", [])) == 7)
        ck("30-day forecast present", len(data.get("forecast", [])) == 30)
        # The single most important check: the dashboard must show the same total as the
        # warehouse. A formatting bug that divides by the wrong constant would be invisible.
        tot = data["kpis"]["TotalSales"]
        ck("Total sales matches gold layer", abs(tot - 65_521_298.75) < 0.01,
           f"R{tot:,.2f}")
        # 101,843 / 120,969 = 0.8418934
        ck("Redemption rate matches gold layer",
           abs(data["kpis"]["RedemptionRate"] - 101_843 / 120_969) < 1e-9,
           f"{data['kpis']['RedemptionRate']:.4%}")

# Balanced structural tags
for tag in ["div", "svg", "table", "script", "style"]:
    o = len(re.findall(rf"<{tag}[\s>]", html))
    c = len(re.findall(rf"</{tag}>", html))
    ck(f"Balanced <{tag}> tags", o == c, f"{o} open / {c} close")

# ---------------------------------------------------------------------------------------
# Reference check: every `D.<key>` the JavaScript reads must exist in the payload.
# This is the failure that actually happens in practice — a chart silently renders empty
# because a key was renamed in Python and not in the JS. Balanced tags would not catch it.
# ---------------------------------------------------------------------------------------
script = re.search(r"<script>\n(.*)</script>", html, re.S).group(1)
top_refs = set(re.findall(r"\bD\.([A-Za-z_]\w*)", script))
bad = sorted(top_refs - set(data.keys()))
ck("Every D.<key> reference resolves", not bad,
   f"unresolved={bad}" if bad else f"{len(top_refs)} distinct keys read")

# Second level: D.ml.* and D.kpis.* and D.confounder.* etc.
nested_bad = []
for parent in ["ml", "kpis", "confounder", "concentration", "answers", "recon", "targetCal"]:
    if parent not in data or not isinstance(data[parent], dict):
        continue
    for child in set(re.findall(rf"\bD\.{parent}\.([A-Za-z_]\w*)", script)):
        if child not in data[parent]:
            nested_bad.append(f"D.{parent}.{child}")
# D.ml.<model>.<metric>
for model in ["redemption_propensity", "sales_forecast", "resolution_time",
              "anomaly_detection", "segmentation"]:
    if model not in data.get("ml", {}):
        continue
    for child in set(re.findall(rf"\b(?:rp|sf|ml)\.{model}\.([A-Za-z_]\w*)", script)):
        if child not in data["ml"][model]:
            nested_bad.append(f"ml.{model}.{child}")
for alias, model in [("rp", "redemption_propensity"), ("sf", "sales_forecast")]:
    for child in set(re.findall(rf"\b{alias}\.([A-Za-z_]\w*)", script)):
        if child not in data["ml"][model]:
            nested_bad.append(f"{alias}({model}).{child}")
ck("Every nested data reference resolves", not nested_bad,
   f"unresolved={sorted(set(nested_bad))}" if nested_bad else "checked ml/kpis/answers/etc")

ck("Record arrays are non-empty",
   all(len(data.get(a, [])) > 0 for a in ["merchants", "region", "trend", "voucherType",
                                          "priority", "anomalies", "alerts", "events"]))

# Column-level check on the two widest tables, where a renamed field is most likely
for arr, expected in [
    ("merchants", ["Merchant", "Region", "Channel", "TotalSales", "SalesShare",
                   "CumulativeShare", "TotalTransactions", "AvgBasketValue", "RedemptionRate",
                   "AvgDaysToRedeem", "Tickets", "TicketsPer1kTxn", "SLABreachRate",
                   "MoMChange", "SalesVsPrior3Avg", "HealthScore", "HealthBand", "SalesRank",
                   "LatestMonthSales", "RevenueAtRiskAnnualised", "FocusPriorityScore",
                   "TicketsVsPrior3Avg"]),
    ("anomalies", ["Merchant", "Region", "YearMonth", "AnomalyScore", "SalesValue",
                   "SalesVsOwnHistory", "Tickets", "Explanation"]),
]:
    miss = [c for c in expected if c not in data[arr][0]]
    ck(f"{arr}: all rendered columns present", not miss, f"missing={miss}" if miss else
       f"{len(expected)} columns")

# Node syntax check on the extracted script
node = shutil.which("node")
if node:
    script = re.search(r"<script>\n(.*)</script>", html, re.S).group(1)
    tmp = ROOT / "report" / "_syntax_check.js"
    # Strip DOM calls so the parser sees pure syntax without needing a browser
    tmp.write_text(script, encoding="utf-8")
    r = subprocess.run([node, "--check", str(tmp)], capture_output=True, text=True)
    ck("JavaScript parses without syntax errors", r.returncode == 0,
       r.stderr.strip().splitlines()[0] if r.returncode else "node --check")
    tmp.unlink()
else:
    print("  SKIP  Node not available for JS syntax check")

failed = sum(1 for _, c, _ in checks if not c)
print("=" * 90)
print(f"{len(checks) - failed}/{len(checks)} checks passed")
print("=" * 90)
